### ISSUE TITLE
 npm install @editorjs/dom  doesn't work

### ISSUE THREAD

**Issue by aavishkarmishra** [editor-js/utils#16]
Issue : 
npm install @editorjs/dom    
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:^

Suggested solution :
Add workspaces in package.json 
```
{
  "workspaces": [
    "packages/*"
  ]
}

```

Resolves : **https://github.com/editor-js/quote/issues/68**

Reference https://yarnpkg.com/features/workspaces#:~:text=To%20declare%20a%20workspace%2C%20all,packages%20folder%20will%20become%20workspaces.

@neSpecc

**Comment by e11sy** [comment]
that was a breaking change for 0.0.4 and lower versions of all utils since 0.0.5 it is solved
published package do not reference workspaces anymore
![image](https://github.com/user-attachments/assets/a34bd594-c574-4013-a094-df4b0b87200d)
![image](https://github.com/user-attachments/assets/d387103e-166e-4fb7-8f4d-31f899a524dd)
